[package]
name = "ndc"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Jerry"]

[[bin]]
path = "main.rs"
name = "ndc"

[dev-dependencies]
tempfile = "3"

[dependencies]
ndc-interface = { path = "../crates/interface" }
ndc-runtime = { path = "../crates/runtime" }
tokio = { version = "1", features = ["full"] }
